// Hierarchy and mapping definitions for SuperSlicer to OrcaSlicer
// This file is the foundation for conversion logic

export const systemDirectories = {
  os: {
    linux: ['.config'],
    MSWin32: ['AppData', 'Roaming'],
    darwin: ['Library', 'Application Support']
  },
  input: {
    Filament: 'filament',
    Print: 'print',
    Printer: 'printer'
  },
  output: {
    filament: ['user', 'default', 'filament'],
    print: ['user', 'default', 'process'],
    printer: ['user', 'default', 'machine']
  }
};

export const illegalChars = {
  MSWin32: /[<>:"\/\\|?*\x00-\x1F]/,
  darwin: /[:]/,
  linux: /\//
};

export const parameterMap = {
  print: {
    arc_fitting: 'enable_arc_fitting',
    bottom_solid_layers: 'bottom_shell_layers',
    bottom_solid_min_thickness: 'bottom_shell_thickness',
    bridge_acceleration: 'bridge_acceleration',
    bridge_angle: 'bridge_angle',
    bridge_overlap_min: 'bridge_density',
    dont_support_bridges: 'bridge_no_support',
    bridge_speed_internal: 'internal_bridge_speed',
    brim_ears: 'brim_ears',
    brim_ears_detection_length: 'brim_ears_detection_length',
    brim_ears_max_angle: 'brim_ears_max_angle',
    brim_separation: 'brim_object_gap',
    brim_width: 'brim_width',
    brim_speed: 'skirt_speed',
    compatible_printers_condition: 'compatible_printers_condition',
    compatible_printers: 'compatible_printers',
    default_acceleration: 'default_acceleration',
    overhangs: 'detect_overhang_wall',
    thin_walls: 'detect_thin_wall',
    draft_shield: 'draft_shield',
    first_layer_size_compensation: 'elefant_foot_compensation',
    elefant_foot_compensation: 'elefant_foot_compensation',
    enable_dynamic_overhang_speeds: 'enable_overhang_speed',
    extra_perimeters_on_overhangs: 'extra_perimeters_on_overhangs',
    extra_perimeters_odd_layers: 'alternate_extra_wall',
    wipe_tower: 'enable_prime_tower',
    wipe_speed: 'wipe_speed',
    ensure_vertical_shell_thickness: 'ensure_vertical_shell_thickness',
    gap_fill_min_length: 'filter_out_gap_fill',
    gcode_comments: 'gcode_comments',
    gcode_label_objects: 'gcode_label_objects',
    machine_limits_usage: 'emit_machine_limits_to_gcode',
    infill_anchor_max: 'infill_anchor_max',
    infill_anchor: 'infill_anchor',
    fill_angle: 'infill_direction',
    infill_overlap: 'infill_wall_overlap',
    infill_first: 'is_infill_first',
    inherits: 'inherits',
    extrusion_width: 'line_width',
    extrusion_multiplier: 'print_flow_ratio',
    first_layer_acceleration: 'initial_layer_acceleration',
    first_layer_extrusion_width: 'initial_layer_line_width',
    first_layer_height: 'initial_layer_print_height',
    interface_shells: 'interface_shells',
    perimeter_extrusion_width: 'inner_wall_line_width',
    seam_gap: 'seam_gap',
    solid_infill_acceleration: 'internal_solid_infill_acceleration',
    solid_infill_extrusion_width: 'internal_solid_infill_line_width',
    ironing_flowrate: 'ironing_flow',
    ironing_spacing: 'ironing_spacing',
    ironing_speed: 'ironing_speed',
    layer_height: 'layer_height',
    init_z_rotate: 'preferred_orientation',
    spiral_vase: 'spiral_mode',
    solid_infill_extruder: 'solid_infill_filament',
    support_material_extruder: 'support_filament',
    infill_extruder: 'sparse_infill_filament',
    perimeter_extruder: 'wall_filament',
    first_layer_extruder: 'first_layer_filament',
    support_material_interface_extruder: 'support_interface_filament',
    avoid_crossing_perimeters_max_detour: 'max_travel_detour_distance',
    min_bead_width: 'min_bead_width',
    min_feature_size: 'min_feature_size',
    solid_infill_below_area: 'minimum_sparse_infill_area',
    only_one_perimeter_first_layer: 'only_one_wall_first_layer',
    only_one_perimeter_top: 'only_one_wall_top',
    ooze_prevention: 'ooze_prevention',
    extra_perimeters_overhangs: 'extra_perimeters_on_overhangs',
    overhangs_reverse: 'overhang_reverse',
    overhangs_reverse_threshold: 'overhang_reverse_threshold',
    perimeter_acceleration: 'inner_wall_acceleration',
    external_perimeter_acceleration: 'outer_wall_acceleration',
    external_perimeter_extrusion_width: 'outer_wall_line_width',
    post_process: 'post_process',
    wipe_tower_brim_width: 'prime_tower_brim_width',
    wipe_tower_width: 'prime_tower_width',
    raft_contact_distance: 'raft_contact_distance',
    raft_expansion: 'raft_expansion',
    raft_first_layer_density: 'raft_first_layer_density',
    raft_first_layer_expansion: 'raft_first_layer_expansion',
    raft_layers: 'raft_layers',
    avoid_crossing_perimeters: 'reduce_crossing_wall',
    only_retract_when_crossing_perimeters: 'reduce_infill_retraction',
    resolution: 'resolution',
    seam_position: 'seam_position',
    skirt_distance: 'skirt_distance',
    skirt_height: 'skirt_height',
    skirts: 'skirt_loops',
    slice_closing_radius: 'slice_closing_radius',
    slicing_mode: 'slicing_mode',
    small_perimeter_min_length: 'small_perimeter_threshold',
    infill_acceleration: 'sparse_infill_acceleration',
    fill_density: 'sparse_infill_density',
    infill_extrusion_width: 'sparse_infill_line_width',
    staggered_inner_seams: 'staggered_inner_seams',
    standby_temperature_delta: 'standby_temperature_delta',
    hole_to_polyhole: 'hole_to_polyhole',
    hole_to_polyhole_threshold: 'hole_to_polyhole_threshold',
    hole_to_polyhole_twisted: 'hole_to_polyhole_twisted',
    support_material: 'enable_support',
    support_material_angle: 'support_angle',
    support_material_enforce_layers: 'enforce_support_layers',
    support_material_spacing: 'support_base_pattern_spacing',
    support_material_contact_distance: 'support_top_z_distance',
    first_layer_size_compensation_layers: 'elefant_foot_compensation_layers',
    support_material_bottom_contact_distance: 'support_bottom_z_distance',
    support_material_bottom_interface_layers: 'support_interface_bottom_layers',
    support_material_interface_contact_loops: 'support_interface_loop_pattern',
    support_material_interface_spacing: 'support_interface_spacing',
    support_material_interface_layers: 'support_interface_top_layers',
    support_material_extrusion_width: 'support_line_width',
    support_material_buildplate_only: 'support_on_build_plate_only',
    support_material_threshold: 'support_threshold_angle',
    thick_bridges: 'thick_bridges',
    top_solid_layers: 'top_shell_layers',
    top_solid_min_thickness: 'top_shell_thickness',
    top_solid_infill_acceleration: 'top_surface_acceleration',
    top_infill_extrusion_width: 'top_surface_line_width',
    min_width_top_surface: 'min_width_top_surface',
    travel_acceleration: 'travel_acceleration',
    travel_speed_z: 'travel_speed_z',
    travel_speed: 'travel_speed',
    support_tree_angle: 'tree_support_branch_angle',
    support_tree_angle_slow: 'tree_support_angle_slow',
    support_tree_branch_diameter: 'tree_support_branch_diameter',
    support_tree_branch_diameter_angle: 'tree_support_branch_diameter_angle',
    support_tree_branch_diameter_double_wall: 'tree_support_branch_diameter_double_wall',
    support_tree_tip_diameter: 'tree_support_tip_diameter',
    support_tree_top_rate: 'tree_support_top_rate',
    wall_distribution_count: 'wall_distribution_count',
    perimeter_generator: 'wall_generator',
    perimeters: 'wall_loops',
    wall_transition_angle: 'wall_transition_angle',
    wall_transition_filter_deviation: 'wall_transition_filter_deviation',
    wall_transition_length: 'wall_transition_length',
    wipe_tower_no_sparse_layers: 'wipe_tower_no_sparse_layers',
    xy_size_compensation: 'xy_contour_compensation',
    z_offset: 'z_offset',
    xy_inner_size_compensation: 'xy_hole_compensation',
    support_material_layer_height: 'independent_support_layer_height',
    fill_pattern: 'sparse_infill_pattern',
    solid_fill_pattern: 'internal_solid_infill_pattern',
    output_filename_format: 'filename_format',
    support_material_pattern: 'support_base_pattern',
    support_material_interface_pattern: 'support_interface_pattern',
    top_fill_pattern: 'top_surface_pattern',
    support_material_xy_spacing: 'support_object_xy_distance',
    fuzzy_skin_point_dist: 'fuzzy_skin_point_distance',
    fuzzy_skin_thickness: 'fuzzy_skin_thickness',
    fuzzy_skin: 'fuzzy_skin',
    bottom_fill_pattern: 'bottom_surface_pattern',
    bridge_flow_ratio: 'bridge_flow',
    fill_top_flow_ratio: 'top_solid_infill_flow_ratio',
    first_layer_flow_ratio: 'bottom_solid_infill_flow_ratio',
    infill_every_layers: 'infill_combination',
    complete_objects: 'print_sequence',
    brim_type: 'brim_type',
    notes: 'notes',
    support_material_style: 'support_style',
    ironing: 'ironing',
    ironing_type: 'ironing_type',
    ironing_angle: 'ironing_angle',
    external_perimeters_first: 'external_perimeters_first',
    infill_first: 'infill_first',
    remaining_times: 'disable_m73'
  },
  filament: {
    bed_temperature: [
      'hot_plate_temp', 'cool_plate_temp',
      'eng_plate_temp', 'textured_plate_temp'
    ],
    bridge_fan_speed: 'bridge_fan_speed',
    cooling: 'cooling',
    disable_fan_first_layers: 'disable_fan_first_layers',
    end_filament_gcode: 'filament_end_gcode',
    extrusion_multiplier: 'filament_flow_ratio',
    fan_always_on: 'fan_always_on',
    fan_below_layer_time: 'fan_below_layer_time',
    filament_colour: 'default_filament_colour',
    filament_cooling_final_speed: 'filament_cooling_final_speed',
    filament_cooling_initial_speed: 'filament_cooling_initial_speed',
    filament_cooling_moves: 'filament_cooling_moves',
    filament_cost: 'filament_cost',
    filament_density: 'filament_density',
    filament_deretract_speed: 'filament_deretraction_speed',
    filament_diameter: 'filament_diameter',
    filament_load_time: 'filament_load_time',
    filament_loading_speed: 'filament_loading_speed',
    filament_loading_speed_start: 'filament_loading_speed_start',
    filament_max_volumetric_speed: 'filament_max_volumetric_speed',
    filament_minimal_purge_on_wipe_tower: 'filament_minimal_purge_on_wipe_tower',
    filament_notes: 'filament_notes',
    filament_ramming_parameters: 'filament_ramming_parameters',
    filament_retract_before_travel: 'filament_retraction_minimum_travel',
    filament_retract_before_wipe: 'filament_retract_before_wipe',
    filament_retract_layer_change: 'filament_retract_when_changing_layer',
    filament_retract_length: 'filament_retraction_length',
    filament_retract_lift: 'filament_z_hop',
    filament_retract_lift_above: 'filament_retract_lift_above',
    filament_retract_lift_below: 'filament_retract_lift_below',
    filament_retract_restart_extra: 'filament_retract_restart_extra',
    filament_retract_speed: 'filament_retraction_speed',
    filament_shrink: 'filament_shrink',
    filament_settings_id: 'filament_settings_id',
    filament_soluble: 'filament_soluble',
    filament_spool_weight: 'filament_spool_weight',
    filament_toolchange_delay: 'filament_toolchange_delay',
    filament_type: 'filament_type',
    filament_unload_time: 'filament_unload_time',
    filament_unloading_speed: 'filament_unloading_speed',
    filament_unloading_speed_start: 'filament_unloading_speed_start',
    filament_vendor: 'filament_vendor',
    filament_wipe: 'filament_wipe',
    first_layer_bed_temperature: 'first_layer_bed_temperature',
    first_layer_temperature: 'first_layer_temperature',
    full_fan_speed_layer: 'full_fan_speed_layer',
    inherits: 'inherits',
    max_fan_speed: 'max_fan_speed',
    min_fan_speed: 'min_fan_speed',
    min_print_speed: 'min_print_speed',
    slowdown_below_layer_time: 'slowdown_below_layer_time',
    start_filament_gcode: 'filament_start_gcode',
    toolchange_gcode: 'change_filament_gcode',
    default_filament_profile: 'default_filament_profile',
    temperature: 'temperature',
    compatible_printers: 'compatible_printers',
    compatible_printers_condition: 'compatible_printers_condition',
    compatible_prints: 'compatible_prints',
    compatible_prints_condition: 'compatible_prints_condition'
    // Add more as needed from Perl mapping
  },
  printer: {
    bed_custom_model: 'bed_custom_model',
    bed_custom_texture: 'bed_custom_texture',
    before_layer_gcode: 'before_layer_change_gcode',
    toolchange_gcode: 'change_filament_gcode',
    default_filament_profile: 'default_filament_profile',
    default_print_profile: 'default_print_profile',
    deretract_speed: 'deretraction_speed',
    gcode_flavor: 'gcode_flavor',
    inherits: 'inherits',
    layer_gcode: 'layer_change_gcode',
    feature_gcode: 'change_extrusion_role_gcode',
    end_gcode: 'machine_end_gcode',
    machine_max_acceleration_e: 'machine_max_acceleration_e',
    machine_max_acceleration_extruding: 'machine_max_acceleration_extruding',
    machine_max_acceleration_retracting: 'machine_max_acceleration_retracting',
    machine_max_acceleration_travel: 'machine_max_acceleration_travel',
    machine_max_acceleration_x: 'machine_max_acceleration_x',
    machine_max_acceleration_y: 'machine_max_acceleration_y',
    machine_max_acceleration_z: 'machine_max_acceleration_z',
    machine_max_feedrate_e: 'machine_max_speed_e',
    machine_max_feedrate_x: 'machine_max_speed_x',
    machine_max_feedrate_y: 'machine_max_speed_y',
    machine_max_feedrate_z: 'machine_max_speed_z',
    machine_max_jerk_e: 'machine_max_jerk_e',
    machine_max_jerk_x: 'machine_max_jerk_x',
    machine_max_jerk_y: 'machine_max_jerk_y',
    machine_max_jerk_z: 'machine_max_jerk_z',
    machine_min_extruding_rate: 'machine_min_extruding_rate',
    machine_min_travel_rate: 'machine_min_travel_rate',
    pause_print_gcode: 'machine_pause_gcode',
    start_gcode: 'machine_start_gcode',
    max_layer_height: 'max_layer_height',
    min_layer_height: 'min_layer_height',
    nozzle_diameter: 'nozzle_diameter',
    print_host: 'print_host',
    printer_notes: 'printer_notes',
    bed_shape: 'printable_area',
    max_print_height: 'printable_height',
    printer_technology: 'printer_technology',
    printer_variant: 'printer_variant',
    retract_before_wipe: 'retract_before_wipe',
    retract_length_toolchange: 'retract_length_toolchange',
    retract_restart_extra_toolchange: 'retract_restart_extra_toolchange',
    retract_restart_extra: 'retract_restart_extra',
    retract_layer_change: 'retract_when_changing_layer',
    retract_length: 'retraction_length',
    retract_lift: 'z_hop',
    retract_lift_top: 'retract_lift_enforce',
    retract_before_travel: 'retraction_minimum_travel',
    retract_speed: 'retraction_speed',
    silent_mode: 'silent_mode',
    single_extruder_multi_material: 'single_extruder_multi_material',
    thumbnails: 'thumbnails',
    thumbnails_format: 'thumbnails_format',
    template_custom_gcode: 'template_custom_gcode',
    use_firmware_retraction: 'use_firmware_retraction',
    use_relative_e_distances: 'use_relative_e_distances',
    wipe: 'wipe'
  },
  physical_printer: {
    host_type: 1,
    print_host: 1,
    printer_technology: 1,
    printhost_apikey: 1,
    printhost_authorization_type: 1,
    printhost_cafile: 1,
    printhost_password: 1,
    printhost_port: 1,
    printhost_ssl_ignore_revoke: 1,
    printhost_user: 1,
  }
};

export const multivalueParams = {
  max_layer_height: 'single',
  min_layer_height: 'single',
  deretract_speed: 'single',
  default_filament_profile: 'single',
  machine_max_acceleration_e: 'array',
  machine_max_acceleration_extruding: 'array',
  machine_max_acceleration_extruding: 'array',
  machine_max_acceleration_retracting: 'array',
  machine_max_acceleration_travel: 'array',
  machine_max_acceleration_x: 'array',
  machine_max_acceleration_y: 'array',
  machine_max_acceleration_z: 'array',
  machine_max_feedrate_e: 'array',
  machine_max_feedrate_x: 'array',
  machine_max_feedrate_y: 'array',
  machine_max_feedrate_z: 'array',
  machine_max_jerk_e: 'array',
  machine_max_jerk_x: 'array',
  machine_max_jerk_y: 'array',
  machine_max_jerk_z: 'array',
  machine_min_extruding_rate: 'array',
  machine_min_travel_rate: 'array',
  nozzle_diameter: 'single',
  bed_shape: 'array',
  retract_before_wipe: 'single',
  retract_length_toolchange: 'single',
  retract_restart_extra_toolchange: 'single',
  retract_restart_extra: 'single',
  retract_layer_change: 'single',
  retract_length: 'single',
  retract_lift: 'single',
  retract_before_travel: 'single',
  retract_speed: 'single',
  thumbnails: 'array',
  extruder_offset: 'single',
  retract_lift_above: 'single',
  retract_lift_below: 'single',
  wipe: 'single',
};

export const filamentTypes = {
  PET: 'PETG',
  FLEX: 'TPU',
  NYLON: 'PA'
};

export const defaultMVS = {
  PLA: '15',
  PET: '10',
  ABS: '12',
  ASA: '12',
  FLEX: '3.2',
  NYLON: '12',
  PVA: '12',
  PC: '12',
  PSU: '8',
  HIPS: '8',
  EDGE: '8',
  NGEN: '8',
  PP: '8',
  PEI: '8',
  PEEK: '8',
  PEKK: '8',
  POM: '8',
  PVDF: '8',
  SCAFF: '8'
};

export const speedSequence = [
  'perimeter_speed',
  'external_perimeter_speed',
  'solid_infill_speed',
  'infill_speed',
  'small_perimeter_speed',
  'top_solid_infill_speed',
  'gap_fill_speed',
  'support_material_speed',
  'support_material_interface_speed',
  'bridge_speed',
  'first_layer_speed',
  'first_layer_infill_speed'
];
export const speedParams = {
  perimeter_speed: 'inner_wall_speed',
  external_perimeter_speed: 'outer_wall_speed',
  small_perimeter_speed: 'small_perimeter_speed',
  solid_infill_speed: 'internal_solid_infill_speed',
  infill_speed: 'sparse_infill_speed',
  top_solid_infill_speed: 'top_surface_speed',
  gap_fill_speed: 'gap_infill_speed',
  support_material_speed: 'support_speed',
  support_material_interface_speed: 'support_interface_speed',
  bridge_speed: 'bridge_speed',
  first_layer_speed: 'initial_layer_speed',
  first_layer_infill_speed: 'initial_layer_infill_speed'
};

export const seamPositions = {
  cost: 'nearest',
  random: 'random',
  allrandom: 'random',
  aligned: 'aligned',
  contiguous: 'aligned',
  rear: 'back',
  nearest: 'nearest'
};

export const infillTypes = {
  '3dhoneycomb': '3dhoneycomb',
  adaptivecubic: 'adaptivecubic',
  alignedrectilinear: 'alignedrectilinear',
  archimedeanchords: 'archimedeanchords',
  concentric: 'concentric',
  concentricgapfill: 'concentric',
  cubic: 'cubic',
  grid: 'grid',
  gyroid: 'gyroid',
  hilbertcurve: 'hilbertcurve',
  honeycomb: 'honeycomb',
  lightning: 'lightning',
  line: 'line',
  monotonic: 'monotonic',
  monotonicgapfill: 'monotonic',
  monotoniclines: 'monotonicline',
  octagramspiral: 'octagramspiral',
  rectilinear: 'zig-zag',
  rectilineargapfill: 'zig-zag',
  rectiwithperimeter: 'zig-zag',
  sawtooth: 'zig-zag',
  scatteredrectilinear: 'zig-zag',
  smooth: 'monotonic',
  smoothhilbert: 'hilbertcurve',
  smoothtriple: 'triangles',
  stars: 'tri-hexagon',
  supportcubic: 'supportcubic',
  triangles: 'triangles'
};

export const supportStyles = {
  grid: [ 'normal', 'grid' ],
  snug: [ 'normal', 'snug' ],
  tree: [ 'tree',   'default' ],
  organic: [ 'tree',   'organic' ]
};

export const supportPatterns = {
  rectilinear: 1,
  'rectilinear-grid': 1,
  honeycomb: 1,
  lightning: 1,
  default: 1,
  hollow: 1
};

export const interfacePatterns = {
  auto: 1,
  rectilinear: 1,
  concentric: 1,
  rectilinear_interlaced: 1,
  grid: 1
};

export const gcodeFlavors = {
  klipper: 'klipper',
  mach3: 'reprapfirmware',
  machinekit: 'reprapfirmware',
  makerware: 'reprapfirmware',
  marlin: 'marlin',
  marlin2: 'marlin2',
  'no-extrusion': 'reprapfirmware',
  repetier: 'reprapfirmware',
  reprap: 'reprapfirmware',
  reprapfirmware: 'reprapfirmware',
  sailfish: 'reprapfirmware',
  smoothie: 'reprapfirmware',
  teacup: 'reprapfirmware',
  sprinter: 'reprapfirmware',
};

export const hostTypes = {
  repetier: 'repetier',
  prusalink: 'prusalink',
  prusaconnect: 'prusaconnect',
  octoprint: 'octoprint',
  moonraker: 'octoprint',
  mks: 'mks',
  klipper: 'octoprint',
  flashair: 'flashair',
  duet: 'duet',
  astrobox: 'astrobox',
};

export const zhopEnforcement = {
  'All surfaces': 'All Surfaces',
  'Not on top': 'Bottom Only',
  'Only on top': 'Top Only',
};

export const thumbnailFormat = {
  PNG: 'PNG',
  JPG: 'JPG',
  QOI: 'QOI',
  BIQU: 'BTT_TFT',
};
